// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package database

import (
	"context"
	"database/sql"
)

const addCard = `-- name: AddCard :one
INSERT INTO cards (fragrantica_id, url, image, found, downloaded)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING fragrantica_id, url, image, found, downloaded
`

type AddCardParams struct {
	FragranticaID int32
	Url           string
	Image         sql.NullString
	Found         bool
	Downloaded    sql.NullTime
}

func (q *Queries) AddCard(ctx context.Context, arg AddCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, addCard,
		arg.FragranticaID,
		arg.Url,
		arg.Image,
		arg.Found,
		arg.Downloaded,
	)
	var i Card
	err := row.Scan(
		&i.FragranticaID,
		&i.Url,
		&i.Image,
		&i.Found,
		&i.Downloaded,
	)
	return i, err
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards 
SET image = $2, found = $3, downloaded = $4
WHERE fragrantica_id = $1
RETURNING fragrantica_id, url, image, found, downloaded
`

type UpdateCardParams struct {
	FragranticaID int32
	Image         sql.NullString
	Found         bool
	Downloaded    sql.NullTime
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateCard,
		arg.FragranticaID,
		arg.Image,
		arg.Found,
		arg.Downloaded,
	)
	var i Card
	err := row.Scan(
		&i.FragranticaID,
		&i.Url,
		&i.Image,
		&i.Found,
		&i.Downloaded,
	)
	return i, err
}
