// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package database

import (
	"context"
)

const addCard = `-- name: AddCard :one
INSERT INTO cards (fragrantica_id, url, image, has_card, updated)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW()
)
RETURNING fragrantica_id, url, image, has_card, updated
`

type AddCardParams struct {
	FragranticaID int32
	Url           string
	Image         string
	HasCard       bool
}

func (q *Queries) AddCard(ctx context.Context, arg AddCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, addCard,
		arg.FragranticaID,
		arg.Url,
		arg.Image,
		arg.HasCard,
	)
	var i Card
	err := row.Scan(
		&i.FragranticaID,
		&i.Url,
		&i.Image,
		&i.HasCard,
		&i.Updated,
	)
	return i, err
}

const getCard = `-- name: GetCard :one
SELECT fragrantica_id, url, image, has_card, updated
FROM cards
WHERE fragrantica_id = $1
`

func (q *Queries) GetCard(ctx context.Context, fragranticaID int32) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, fragranticaID)
	var i Card
	err := row.Scan(
		&i.FragranticaID,
		&i.Url,
		&i.Image,
		&i.HasCard,
		&i.Updated,
	)
	return i, err
}

const getExistingCardIDs = `-- name: GetExistingCardIDs :many
SELECT fragrantica_id
FROM cards
WHERE has_card = 't'
ORDER BY fragrantica_id ASC
`

func (q *Queries) GetExistingCardIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getExistingCardIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var fragrantica_id int32
		if err := rows.Scan(&fragrantica_id); err != nil {
			return nil, err
		}
		items = append(items, fragrantica_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastCardID = `-- name: GetLastCardID :one
SELECT fragrantica_id
FROM cards
WHERE has_card = 't'
ORDER BY fragrantica_id DESC
LIMIT 1
`

func (q *Queries) GetLastCardID(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLastCardID)
	var fragrantica_id int32
	err := row.Scan(&fragrantica_id)
	return fragrantica_id, err
}

const getMissingCardIDs = `-- name: GetMissingCardIDs :many
SELECT fragrantica_id
FROM cards
WHERE has_card = 'f'
ORDER BY fragrantica_id ASC
`

func (q *Queries) GetMissingCardIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMissingCardIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var fragrantica_id int32
		if err := rows.Scan(&fragrantica_id); err != nil {
			return nil, err
		}
		items = append(items, fragrantica_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshCard = `-- name: RefreshCard :exec
UPDATE cards 
SET downloaded = NOW()
WHERE fragrantica_id = $1
`

func (q *Queries) RefreshCard(ctx context.Context, fragranticaID int32) error {
	_, err := q.db.ExecContext(ctx, refreshCard, fragranticaID)
	return err
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards 
SET image = $2, has_card = $3, updated = NOW()
WHERE fragrantica_id = $1
RETURNING fragrantica_id, url, image, has_card, updated
`

type UpdateCardParams struct {
	FragranticaID int32
	Image         string
	HasCard       bool
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateCard, arg.FragranticaID, arg.Image, arg.HasCard)
	var i Card
	err := row.Scan(
		&i.FragranticaID,
		&i.Url,
		&i.Image,
		&i.HasCard,
		&i.Updated,
	)
	return i, err
}
