// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package database

import (
	"context"
)

const addCard = `-- name: AddCard :one
INSERT INTO cards (fragrantica_id, url, image, has_card, updated)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW()
)
RETURNING fragrantica_id, url, image, has_card, updated
`

type AddCardParams struct {
	FragranticaID int32
	Url           string
	Image         string
	HasCard       bool
}

func (q *Queries) AddCard(ctx context.Context, arg AddCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, addCard,
		arg.FragranticaID,
		arg.Url,
		arg.Image,
		arg.HasCard,
	)
	var i Card
	err := row.Scan(
		&i.FragranticaID,
		&i.Url,
		&i.Image,
		&i.HasCard,
		&i.Updated,
	)
	return i, err
}

const getCard = `-- name: GetCard :one
SELECT fragrantica_id, url, image, has_card, updated
FROM cards
WHERE fragrantica_id = $1
`

func (q *Queries) GetCard(ctx context.Context, fragranticaID int32) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, fragranticaID)
	var i Card
	err := row.Scan(
		&i.FragranticaID,
		&i.Url,
		&i.Image,
		&i.HasCard,
		&i.Updated,
	)
	return i, err
}

const refreshCard = `-- name: RefreshCard :exec
UPDATE cards 
SET downloaded = NOW()
WHERE fragrantica_id = $1
`

func (q *Queries) RefreshCard(ctx context.Context, fragranticaID int32) error {
	_, err := q.db.ExecContext(ctx, refreshCard, fragranticaID)
	return err
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards 
SET image = $2, has_card = $3, updated = NOW()
WHERE fragrantica_id = $1
RETURNING fragrantica_id, url, image, has_card, updated
`

type UpdateCardParams struct {
	FragranticaID int32
	Image         string
	HasCard       bool
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateCard, arg.FragranticaID, arg.Image, arg.HasCard)
	var i Card
	err := row.Scan(
		&i.FragranticaID,
		&i.Url,
		&i.Image,
		&i.HasCard,
		&i.Updated,
	)
	return i, err
}
