// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards_fragrances.sql

package database

import (
	"context"
)

const getMissingFragranceIDs = `-- name: GetMissingFragranceIDs :many
SELECT cards.fragrantica_id
FROM cards
WHERE has_card = 't'
  AND NOT EXISTS (
      SELECT fragrances.fragrantica_id
      FROM fragrances
      WHERE cards.fragrantica_id = fragrances.fragrantica_id
  )
ORDER BY cards.fragrantica_id ASC
`

func (q *Queries) GetMissingFragranceIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMissingFragranceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var fragrantica_id int32
		if err := rows.Scan(&fragrantica_id); err != nil {
			return nil, err
		}
		items = append(items, fragrantica_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
