// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fragrances_perfumers.sql

package database

import (
	"context"
	"database/sql"
)

const getMissingPerfumers = `-- name: GetMissingPerfumers :many
SELECT DISTINCT fragrances.brand
FROM fragrances
WHERE name IS NOT NULL
  AND NOT EXISTS (
      SELECT perfumers.name
      FROM perfumers
      WHERE fragrances.brand = perfumers.name
  )
`

func (q *Queries) GetMissingPerfumers(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getMissingPerfumers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var brand sql.NullString
		if err := rows.Scan(&brand); err != nil {
			return nil, err
		}
		items = append(items, brand)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
