// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: perfumers.sql

package database

import (
	"context"
)

const addPerfumer = `-- name: AddPerfumer :one
INSERT INTO perfumers (name, country)
VALUES (
    $1,
    $2
)
RETURNING name, country
`

type AddPerfumerParams struct {
	Name    string
	Country string
}

func (q *Queries) AddPerfumer(ctx context.Context, arg AddPerfumerParams) (Perfumer, error) {
	row := q.db.QueryRowContext(ctx, addPerfumer, arg.Name, arg.Country)
	var i Perfumer
	err := row.Scan(&i.Name, &i.Country)
	return i, err
}

const getPerfumerCountry = `-- name: GetPerfumerCountry :one
SELECT country
FROM perfumers
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetPerfumerCountry(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPerfumerCountry, name)
	var country string
	err := row.Scan(&country)
	return country, err
}
